image: gitpod/workspace-full

tasks:
  - init: |
      curl https://dlcdn.apache.org/kafka/3.4.0/kafka_2.13-3.4.0.tgz -o kafka.tgz
      tar -xzf kafka.tgz
      rm kafka.tgz
  - name: Zookeeper
    command: |
      cd kafka*/
      bin/zookeeper-server-start.sh config/zookeeper.properties
  - name: Kafka
    command: |
      cd kafka*/
      bin/kafka-server-start.sh config/server.properties
  - name: Producer
    command: |
      cd kafka*/bin
  - name: Consumer
    command: |
      cd kafka*/bin
